In [1]:
import pandas as pd
import numpy as np

In [2]:
sale = pd.read_csv('Train.csv')

In [3]:
sale.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [4]:
sale.shape

(8523, 12)

In [5]:
sale["Item_Fat_Content"].replace(["LF", "low fat", "reg"],["Low Fat", "Low Fat", "Regular"], inplace = True)

In [6]:
sale.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [7]:
sale["Item_Weight"] = sale["Item_Weight"].fillna(sale["Item_Weight"].mean())

In [8]:
sale["Outlet_Size"] = sale["Outlet_Size"].fillna(method = "ffill")

In [9]:
sale.drop(["Outlet_Establishment_Year"],axis = 1,inplace = True)

## Label Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

sale['Item_Identifier'] = label.fit_transform(sale['Item_Identifier'])

sale['Item_Fat_Content'] = label.fit_transform(sale['Item_Fat_Content'])

sale['Item_Type'] = label.fit_transform(sale['Item_Type'])

sale['Outlet_Identifier'] = label.fit_transform(sale['Outlet_Identifier'])

sale['Outlet_Size'] = label.fit_transform(sale['Outlet_Size'])

sale['Outlet_Location_Type'] = label.fit_transform(sale['Outlet_Location_Type'])

sale['Outlet_Type'] = label.fit_transform(sale['Outlet_Type'])

In [11]:
sale.head()

Item_Identifier  Item_Weight  Item_Fat_Content  Item_Visibility  Item_Type  \
0              156         9.30                 0         0.016047          4   
1                8         5.92                 1         0.019278         14   
2              662        17.50                 0         0.016760         10   
3             1121        19.20                 1         0.000000          6   
4             1297         8.93                 0         0.000000          9   

   Item_MRP  Outlet_Identifier  Outlet_Size  Outlet_Location_Type  \
0  249.8092                  9            1                     0   
1   48.2692                  3            1                     2   
2  141.6180                  9            1                     0   
3  182.0950                  0            1                     2   
4   53.8614                  1            0                     2   

   Outlet_Type  Item_Outlet_Sales  
0            1          3735.1380  
1            2           443.4228  
2            1          2097.2700  
3            0           732.3800  
4            1           994.7052

In [12]:
sale.shape

(8523, 11)

In [13]:
x = sale.iloc[:,0:10]
y = sale.iloc[:,10:11]

In [14]:
x.shape

(8523, 10)

In [15]:
y.shape

(8523, 1)

In [16]:
from sklearn.preprocessing import PolynomialFeatures
polynomial_features = PolynomialFeatures(degree = 2)
x_poly = polynomial_features.fit_transform(x)
print(x_poly)

[[1.000e+00 1.560e+02 9.300e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [1.000e+00 8.000e+00 5.920e+00 ... 4.000e+00 4.000e+00 4.000e+00]
 [1.000e+00 6.620e+02 1.750e+01 ... 0.000e+00 0.000e+00 1.000e+00]
 ...
 [1.000e+00 1.357e+03 1.060e+01 ... 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 6.810e+02 7.210e+00 ... 4.000e+00 4.000e+00 4.000e+00]
 [1.000e+00 5.000e+01 1.480e+01 ... 0.000e+00 0.000e+00 1.000e+00]]


## Implement Machine Learning

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_poly,y, test_size = 1/4, random_state = 0)

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(x_train,y_train)

array([[ 0.        , -0.33483083, -0.52221776, ...,  1.21906307,
        -0.84043081, -0.78806564],
       [ 0.        ,  1.62119285, -0.95121868, ...,  1.21906307,
         1.21624366,  0.72748624],
       [ 0.        , -0.98981933, -1.80685686, ..., -1.08497334,
        -0.84043081, -0.40917767],
       ...,
       [ 0.        , -0.17387802,  0.14078365, ..., -0.50896424,
        -0.32626219, -0.40917767],
       [ 0.        , -0.62991097,  1.36987718, ..., -0.50896424,
        -0.32626219, -0.40917767],
       [ 0.        , -0.65226552,  0.25896572, ..., -1.08497334,
        -0.84043081, -0.40917767]])

In [19]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [20]:
reg.fit(x_train,y_train)

LinearRegression()

In [21]:
prediction = reg.predict(x_test)

In [22]:
from sklearn.metrics import mean_squared_error, r2_score
rmse = np.sqrt(mean_squared_error(y_test, prediction))

In [23]:
rmse

1104.869838798016

In [24]:
r2_score(y_test,prediction)

0.5925599205745525

In [25]:
from sklearn.ensemble import GradientBoostingRegressor

In [26]:
model = GradientBoostingRegressor()

In [27]:
model.fit(x_train, y_train)
prediction = model.predict(x_test)

C:\Users\Administrator\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [28]:
from sklearn.metrics import mean_squared_error,r2_score
rmse = np.sqrt(mean_squared_error(y_test,prediction))

In [29]:
## error

In [30]:
rmse

1106.822866890049

In [31]:
## accuracy

In [32]:
r2_score(y_test,prediction)

0.5911182209437976